DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUS_PARSED = "parsed"
DOCUMENT_STATUS_UPLOADED = "uploaded"

EXPENSE_STATUS_APPROVED = "approved"
EXPENSE_STATUS_EXTRACTED = "extracted"
EXPENSE_STATUS_FLAGGED = "flagged"
EXPENSE_STATUS_REJECTED = "rejected"

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"
